# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\git_repos\Python_VP3_LR\DR1\auth1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 236)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(280, 40, 71, 91))
        self.enter_button.setObjectName("enter_button")
        self.author_bottin = QtWidgets.QPushButton(self.centralwidget)
        self.author_bottin.setGeometry(QtCore.QRect(150, 180, 93, 28))
        self.author_bottin.setObjectName("author_bottin")
        self.login_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_edit.setGeometry(QtCore.QRect(140, 50, 113, 22))
        self.login_edit.setObjectName("login_edit")
        self.pass_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_edit.setGeometry(QtCore.QRect(140, 100, 113, 22))
        self.pass_edit.setObjectName("pass_edit")
        self.login = QtWidgets.QLabel(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(70, 50, 55, 16))
        self.login.setObjectName("login")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(70, 100, 55, 16))
        self.password.setObjectName("password")
        self.is_success = QtWidgets.QLabel(self.centralwidget)
        self.is_success.setGeometry(QtCore.QRect(60, 40, 201, 91))
        self.is_success.setObjectName("is_success")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enter_button.setText(_translate("MainWindow", "Войти"))
        self.author_bottin.setText(_translate("MainWindow", "Author info"))
        self.login.setText(_translate("MainWindow", "Логин"))
        self.password.setText(_translate("MainWindow", "Пароль"))
        self.is_success.setVisible(False)
        self.is_success.setStyleSheet('font-size: 12pt; font-weight: 36;')
        self.is_success.setText(_translate("MainWindow", "Вход выполнен \nуспешно!"))
